### ISSUE TITLE
Допил станции.

### ISSUE THREAD

**Issue by Tap0r** [Tap0r/Maper-repo#1]
Пятилетка до Августа:
1. Мостик:
- [x] Аплоуд
- [x] Мостик
- [x] Нюка
- [x] Каюта кэпа
- [x] Кабинет хопа
- [x] Телепортерная
- [x] Серверная
- [x] Станция боргов
- [x] ЕВА
- [x] Гейтвей
- [x] Офис АВД
2. Гражданские отсеки:
- [x] Бар
- [x] Кухня
- [x] Поника
- [x] Театр
- [x] Парихмахерская
- [x] Ассистентская
- [x] Игровая
- [x] Голодек
- [x] Дормы
- [x] Сауна
- [x] Качалка
- [x] Переодевалка
- [x] Кабинет частника
- [x] Крио
- [x] Библиотека
- [x] Церковь
- [x] Парк
- [x] Уборщик
- [x] Суд
3. Рнд:
- [x] Комната брифинга
- [x] Комната отдыха
- [x] Лаборатория
- [x] Робототехника
- [x] Кабинет РД
- [x] Сервера
- [x] Телесайнс
- [x] Токсинная
- [x] Изолятор
- [x] Ксенбио
- [ ] Ксенархо
4. Мед:
- [x] Ресепшен
- [x] Комната со слиперами
- [x] Комната с крио
- [x] Склад
- [x] Химия
- [x] Операционные
- [x] Пациентские
- [x] Кабинет СМО
- [x] Комната отдыха
- [x] Вирусология
- [x] Клонинг лаб
- [x] Генетика
- [x] Морг
- [x] Чекпоинты где-нибудь
4. Инженерный:
- [x] Комната отдыха
- [x] Мониторинговая
- [x] Атмос
- [x] Хранилище экипировки
- [x] СМ
- [x] Дронная
- [x] Хранилище плат
- [x] Труба на спутник к телекомам
- [x] Кабинет СЕ
- [x] Хранилище
- [x] Стройка
- [x] Какие-нибудь заброшенные отсеки
- [x] Соляры
5. Бриг :
- [x] Лобби
- [x] Варден
- [x] Общак
- [x] Офис охраны
- [x] Кабинет ГСБ
- [x] Хранилище эквипа
- [x] Стрельбище
- [x] Оружейная
- [x] Арсенал
- [x] Процедурка
- [x] Допросная
- [x] Комната казни
- [x] Хранилище улик
- [x] Детектив
- [x] Криминалист
- [x] КПП в отбытии
6. Карго:
- [x] Приёмная
- [x] Офис доставки
- [x] Склад
- [x] Кабинет КМа
- [x] Комната шахтёров
- [x] Комната мусорщиков
- [x] Свалка
- [x] Мусоросброс
7. Спутник:
- [x] Ядро
- [x] Телекомы
- [x] Телепортер
- [x] Труба в инженерный
8. Антагонисты:
- [x] Зоны шаттлов в космосе (нюка, воксы)
- [x] Точки спавна в космосе (контрабандист, ниндзя, карпы и тд)
9. Муторный калл:
- [x] Трубы
- [x] Проводка
- [x] Мусорные трубы
- [x] Пожарные створки
- [x] Шлюзы в космос
- Настенные штуки:
- [x] Мостик
- [x] Гражданские
- [x] РнД
- [x] Мед
- [x] Инжир
- [x] Бриг
- [x] Карго
- [x] Спутник

**Comment by Mercurialaste** [comment]
- [ ] Шахтерская конура.

**Comment by Tap0r** [comment]
а ну короче тут саццес получаеца да
